### ISSUE TITLE
vOptSpecific fails to build on julia v0.6.3

### ISSUE THREAD

**Issue by rarygit** [vOptSolver/vOptSpecific.jl#3]
Full output below. It seems to be stuck at 2phrpasf2
Any suggestions to successfully build vOptSpecific are much appreciated.

julia> Pkg.build("vOptSpecific")
INFO: Building vOptSpecific
C:\Users\office\.julia\v0.6\vOptSpecific\deps\LAPgcc -O3 -c -fpic 2phrpasf2.c -o
 2phrpasf2.o
In file included from 2phrpasf2.c:11:0:
2phrpasf2.h:15:10: fatal error: sys/resource.h: No such file or directory
 #include <sys/resource.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:4: 2phrpasf2.o] Error 1
============================[ ERROR: vOptSpecific ]=============================

LoadError: failed process: Process(`make`, ProcessExited(2)) [2]
while loading C:\Users\office\.julia\v0.6\vOptSpecific\deps\build.jl, in express
ion starting on line 1

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: vOptSpecific had build errors.

 - packages with build errors remain installed in C:\Users\office\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("vOptSpecific")`
 - build a single package by running its `deps/build.jl` script

================================================================================

julia>

**Comment by rarygit** [comment]
2phrpasf2.h:  fatal error: sys/resource.h: No such file or directory #include <sys/resource.h>
---> commented out #include <sys/resource.h> in file 2phrpasf2.h

make: pwd: Command not found (referring to EXDIR = $(shell pwd) in Makefile)
--> copied pwd.exe from cygwin/bin to msys/bin

make: *** No rule to make target '/src/Box.cpp', needed by '/obj/Box.o'.  Stop
Is this error related to EXDIR = $(shell pwd) in the Makefile?

Latest error for "build vOptSpecific" as below:

pkg> build vOptSpecific
  Building vOptSpecific → `C:\Users\office\.julia\packages\vOptSpecific\MEJJi\de
ps\build.log`
┌ Error: Error building `vOptSpecific`:
│ gcc -O3 -shared -o ../libLAP.so 2phrpasf2.o
│ make: *** No rule to make target '/src/Box.cpp', needed by '/obj/Box.o'.  Stop
.
│ ERROR: LoadError: failed process: Process(`make`, ProcessExited(2)) [2]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.j
l:42
│  [2] pipeline_error at .\process.jl:712 [inlined]
│  [3] #run#509(::Bool, ::Function, ::Cmd) at .\process.jl:670
│  [4] run at .\process.jl:668 [inlined]
│  [5] (::getfield(Main, Symbol("##5#6")))() at C:\Users\office\.julia\packages\
vOptSpecific\MEJJi\deps\build.jl:6
│  [6] cd(::getfield(Main, Symbol("##5#6")), ::String) at .\file.jl:85
│  [7] top-level scope at none:0
│  [8] include at .\boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] include(::String) at .\client.jl:398
│  [12] top-level scope at none:0
│ in expression starting at C:\Users\office\.julia\packages\vOptSpecific\MEJJi\d
eps\build.jl:5
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\bu
ild\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068

**Comment by gsoleilhac** [comment]
vOptSpecific only support Linux and MacOS at the moment, I haven't managed to compile and call C shared libraries from Julia on Windows.

**Comment by rarygit** [comment]
Thanks for the reply!
Now I have successfully installed vOptSpecific on Julia v0.6.4, Windows 8, and all tests passed.
Solution as follows (although vOptGeneric still fails tests on Julia v0.6.4):

(a) File "2phrpasf2.h": comment out line 15   /* #include <sys/resource.h> */
(b) Copied pwd.exe from c:/cygwin/bin to c:/msys/bin
(c) Makefile in folder UMFLP:  replace EXDIR = $(shell pwd) with absolute paths to folders. Create folders for res, lib, plot. See below:

	#===========================MakeFile==============================
# To compile 
#================================================================

EXDIR = $(shell pwd)


# ---------------------------------------------------------------------
# Compiler selection 
# ---------------------------------------------------------------------

CCC = g++

# ---------------------------------------------------------------------
# Compiler options 
# ---------------------------------------------------------------------

CCOPT = -Ofast -Wall -Wextra -g -fPIC

#------------------------------------------------------------
#
# Build and Execute directory
#
#------------------------------------------------------------

LIB_PATH = C:/Users/office/.julia/v0.6/vOptSpecific/deps/UMFLP/lib
SRC_PATH = C:/Users/office/.julia/v0.6/vOptSpecific/deps/UMFLP/src
OBJ_PATH = C:/Users/office/.julia/v0.6/vOptSpecific/deps/UMFLP/obj
RES_PATH = C:/Users/office/.julia/v0.6/vOptSpecific/deps/UMFLP/res
PLO_PATH = C:/Users/office/.julia/v0.6/vOptSpecific/deps/UMFLP/plot
